---
'GitHub Actions':
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**/*
      - any-glob-to-any-file: .github/scripts/**/*
      - any-glob-to-any-file: .github/dependabot.yml
      - any-glob-to-any-file: .github/labeler.yml
      - any-glob-to-any-file: .github/.typos_config.toml
