---
name: Create Release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create_release:
    # See: .github/workflows/create_release_pr.yaml
    if: ${{ github.head_ref == 'prepare_for_release' && github.event.pull_request.merged == true }}
    env:
      RELEASE_DESCRIPTION_TXT_FILE: release_description.txt
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - uses: dart-lang/setup-dart@v1

      - name: inject current version
        run: echo "CURRENT_VERSION=$(dart pub deps --style compact | grep "dart-boilerplate" | grep -Eo '[0-9]{1,}.[0-9]{1,}.[0-9]{1,}')" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          generate_release_notes: true
