---
name: Dart CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dart_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: dart format
        run: dart run grinder format # Replaced

  dart_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: analyzer
        run: dart run grinder analyze # Replaced

  dart_test:
    needs: [dart_format, dart_analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: run test
        run: dart run grinder test # Replaced
      - name: coverage
        run: dart run grinder coverage # Replaced
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
