---
name: Dart CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dart_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: dart format
        run: dart format ./ --set-exit-if-changed

  dart_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: analyzer
        run: dart analyze --fatal-infos --fatal-warnings .

  dart_test:
    needs: [dart_format, dart_analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: run test
        run: dart run test . --coverage=coverage
      - name: coverage
        run: dart run coverage:format_coverage --lcov --in coverage --out lcov.info
      - uses: codecov/codecov-action@v5
        with:
          file: lcov.info
