name: Dart CI

on:
  pull_request:
    paths: ['**.dart', 'pubspec.*', 'analysis_options.yaml', '.github/workflows/dart_ci.yaml']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', 'analysis_options.yaml', '.github/workflows/dart_ci.yaml']

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: beta
    - name: dart format
      run: dart format ./ -l 120 --set-exit-if-changed

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: beta
    - name: install dependencies
      run: dart pub get
    - name: analyzer
      run: dart analyze --fatal-infos --fatal-warnings .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: beta
    - name: install dependencies
      run: dart pub get
    - name: run test
      run: dart pub run test . --coverage=coverage
    - name: coverage
      run: dart pub run coverage:format_coverage --lcov --packages=.packages --in coverage --out lcov.info
    - uses: codecov/codecov-action@v2.0.3
      with:
        file: lcov.info
